### ISSUE TITLE
ConnectionError

### ISSUE THREAD

**Issue by khamaileon** [ksamuel/music_story_python_sdk#1]
I'm facing a ConnectionError when trying to authenticate to the Music Story API. (Python 3.5.3 - Requests 2.13.0)
```python
api = MusicStoryApi(MUSICSTORY_KEY, MUSICSTORY_SECRET)
api.connect()
```
```
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```
Any idea on how to solve it?

**Comment by khamaileon** [comment]
New error message this morning:
```
Traceback (most recent call last):
  File "/home/david/workspace/me/my-project/api/musicstory/tests.py", line 11, in test_authentication
    self.api.connect()
  File "/home/david/.virtualenvs/my-project/lib/python3.5/site-packages/music_story/api.py", line 61, in connect
    response = session.fetch_request_token(self.url('fetch_token'))
  File "/home/david/.virtualenvs/my-project/lib/python3.5/site-packages/requests_oauthlib/oauth1_session.py", line 268, in fetch_request_token
    token = self._fetch_token(url, **request_kwargs)
  File "/home/david/.virtualenvs/my-project/lib/python3.5/site-packages/music_story/music_story_oauth.py", line 53, in _fetch_token
    "Unable to decode JSON from %s. Check you are not using the "
music_story.music_story_oauth.MusicStoryApiError: Unable to decode JSON from %s. Check you are not using the XML API and that the request is well formatted.
```

**Comment by dabonneville** [comment]
Hi , 
Same here, any support to be expected @ksamuel ? 
Did you solve your issue @khamaileon ?
Thanks !

**Comment by ksamuel** [comment]
Hello,

A l'époque j'étais payé pour coder cette lib. Je ne travaille plus pour le client depuis longtemps. Néanmoins si quelqu'un souhaite m'embaucher pour en faire la maintenance, c'est possible.

**Comment by dabonneville** [comment]
Hello @ksamuel, merci pour votre message. Le bug est fixé, on va maintenir dans une autre branche.

**Comment by smennetrier** [comment]
Bonjour @ksamuel

J'ai fixé le problème (https://github.com/voxtok/music_story_python/commits/fix_oauth_connection). Si tu n'y vois pas d'inconvénient, je te propose de reprendre la maintenance du sdk.
Si tu es d'accord je te laisse transférer le repository sur le compte @voxtok.

**Comment by ksamuel** [comment]
Ok j'ai tenté ce matin mais j'ai obtenu l'erreur suivante :

voxtok already has a repository in the ksamuel/music_story_python_sdk_official network and You don’t have the permission to create repositories on voxtok 

Je pense qu'il faut que je fasse partie de vortox pour vous donner le compte. Alternativement je peux juste supprimer le compte et vous gardez votre fork.

**Comment by smennetrier** [comment]
Est-il possible alors de le transférer sur mon compte @smennetrier ? Je ferais le necessaire ensuite pour le transférer sur @voxtok.

Merci par avance :)

**Comment by ksamuel** [comment]
Done

**Comment by smennetrier** [comment]
Bonjour @ksamuel,

Tout est OK, merci :-)

**Comment by smennetrier** [comment]
@ksamuel Peux tu aussi me transférer les droits de maintenance du package sur PiPy ? Mon username c'est "smennetrier".

Merci

**Comment by ksamuel** [comment]
ok
